spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: Mysql@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

custom:
  message: Hello World, Spring!
